export const ADD = 'ADD';
export const ADD_USER_INFO = 'ADD_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
export const GET_CACHE_MESSAGELIST = 'GET_CACHE_MESSAGELIST';
export const CLEAR_MESSAGELIST = 'CLEAR_MESSAGELIST';
export const PUSH_MESSAGE = 'PUSH_MESSAGE';
export const READ_MESSAGE = 'READ_MESSAGE';
